name: "Deploy to Valtown"
description: "Deploy to Valtown"

inputs:
  GITHUB_WORKSPACE:
    description: "Github workspace"
    default: ${{ github.workspace }}
    required: false

  VAL_TOWN_API_KEY:
    description: "Valtown API Key"
    default: ${{ secrets.VAL_TOWN_API_KEY }}
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
