name: Test

on: workflow_dispatch

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to workspace
        uses: actions/checkout@v4
      - name: Deploy to ValTown 🚀
        uses: ./
        with:
          VAL_TOWN_API_KEY: ${{ secrets.VAL_TOWN_API_KEY }}